kumuluzee:
  name: rso-comments
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/commentsDS
      connection-url: jdbc:postgresql://192.168.99.100:5434/comment
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://169.51.20.118:30451
  discovery:
    etcd:
      hosts: http://169.51.20.118:30451
  health:
      checks:
        data-source-health-check:
          jndi-name: jdbc/commentsDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: comments-endpoint
        url-pattern: /v1/comments/*
rest-properties:
  external-services:
    order-service:
      enabled: true
  healthy: true
