apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: comment-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
      - image: amela/comments
        name: comments
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-comments:5432/comment
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 10
          periodSeconds: 3
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP
        resources:
          limits:
            cpu: 500m
